---
title: "Interactive ML - Linear Regression"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    vertical_layout: fill
    orientation: columns
runtime: shiny

---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(DT)
library(dplyr)
library(plotly)
library(readr)
library(rvest)
library(lubridate)
library(FSA)
```



```{r data}
setwd("C:/Users/Tarri/Desktop/portfolio_projects/ozone_spat_dashboard")
global_temp <- read_csv("C:/Users/Tarri/Desktop/portfolio_projects/ozone_spat_dashboard/data/global_temp.csv")

ozone_yr_url <- "https://wiki.socr.umich.edu/index.php/SOCR_Data_121608_OzoneData"
wiki_ozone_yr <- read_html(ozone_yr_url) # UCLA SOCR Data
ozone_yr_data <- as.data.frame(html_table(html_nodes(wiki_ozone_yr, "table")[[1]]), header = FALSE)

global_temp <- global_temp %>%
  rename("Date"="Year")
global_temp$Date <- paste(global_temp$Date , "-01-01", sep="")
global_temp$Date <- ymd(global_temp$Date)
global_temp$Date <-  format(as.Date(global_temp$Date, format="%d/%m/%Y"),"%Y")

ozone_yr_data <- ozone_yr_data %>%
  rename("Date"="YEAR")
ozone_yr_data$Date <- paste(ozone_yr_data$Date , "-01-01", sep="")
ozone_yr_data$Date <- ymd(ozone_yr_data$Date)
ozone_yr_data$Date <-  format(as.Date(ozone_yr_data$Date, format="%d/%m/%Y"),"%Y")

ozone_temp <- merge( ozone_yr_data, global_temp, by="Date")
ozone_temp <- subset(ozone_temp, ANNUAL < 5)

ozone_temp$Date <- as.numeric(ozone_temp$Date)

# Generate 90-10% training-testing split of the reviews
all_ids <- ozone_temp$INDEX
train_ids <- sample(all_ids, length(ozone_temp$INDEX)*0.8)
test_ids <- setdiff(all_ids, train_ids)
train <- ozone_temp[ozone_temp$INDEX %in% train_ids , ]
test <- ozone_temp[ozone_temp$INDEX %in% test_ids, ]
ozone_temp <- ozone_temp %>%
    select(-c("INDEX","LOCATION","VARIABLE","COMP_SITES","No_Smoothing"))
set.seed(42)
train <- train%>%
  select(-c("INDEX","LOCATION","VARIABLE","COMP_SITES","No_Smoothing"))
test <- test%>%
  select(-c("INDEX","LOCATION","VARIABLE","COMP_SITES","No_Smoothing"))
test1 <- test %>%
  select(-c("ANNUAL"))

test1 <- as.data.frame(sapply(test1, as.double ))

variables <- colnames(train)

```

Column {.sidebar data-width=200}
-----------------------------------------------------------------

```{r inputs}
 selectInput("variable_choice", label = h5("Choose one or more input variables"), 
             choices = variables, variables[1], multiple = TRUE)
 sliderInput("slider",label=h5("Choose how the training and testing data is split"),
             min =0, max=100, value= 80, step = 10)

```


```{r reactive expression}
model1 <- reactive({
  set.seed(42)
 train_ids <- sample(all_ids, length(ozone_temp$INDEX)*(input$slider/100))
 train <- ozone_temp[ozone_temp$INDEX %in% train_ids , ]
 test <- ozone_temp[ozone_temp$INDEX %in% test_ids, ]
 test1 <- test %>% select(-c("ANNUAL")) 
 vars <- as.matrix(train[, input$variable_choice])
 linear <- lm(ANNUAL ~vars, data = train)
   
})
```

Column {data-width=400}
-----------------------------------------------------------------------

###

```{r model output}
renderPrint({ 
 set.seed(42)
 train_ids <- sample(all_ids, length(ozone_temp$INDEX)*(input$slider/100))
 train <- ozone_temp[ozone_temp$INDEX %in% train_ids , ]
 test <- ozone_temp[ozone_temp$INDEX %in% test_ids, ]
 test1 <- test %>% select(-c("ANNUAL")) 
 vars <- as.matrix(train[, input$variable_choice])
summary(model1())

})
```

###


```{r table}

DT::renderDataTable({
  set.seed(42)
 train_ids <- sample(all_ids, length(ozone_temp$INDEX)*(input$slider/100))
 train <- ozone_temp[ozone_temp$INDEX %in% train_ids , ]
 test <- ozone_temp[ozone_temp$INDEX %in% test_ids, ]
 test1 <- test %>% select(-c("ANNUAL")) 
 vars <- as.matrix(train[, input$variable_choice])
  
   DT::datatable(test1 %>% mutate(predicted = round(predict(model1(),test1), 2 ), actual = test$ANNUAL) %>% select(predicted, actual),
   rownames = FALSE, colnames = c('predicted concentration','actual concentration'), extensions = c('Buttons', 'Responsive'), 
   options = list(columnDefs = list(list(className = 'dt-center', targets = "_all")), dom = 'Blfrt', 
   buttons = c('copy', 'csv', 'excel', 'print'), searching = FALSE, lengthMenu = c(20, 100, 1000, nrow(test1)), scrollY = 300, scrollCollapse = TRUE)) 
  
 })

```

Column {data-width=400}
-----------------------------------------------------------------------

###

```{r scatter}
renderPlotly({
  set.seed(42)
 train_ids <- sample(all_ids, length(ozone_temp$INDEX)*(input$slider/100))
 train <- ozone_temp[ozone_temp$INDEX %in% train_ids , ]
 test <- ozone_temp[ozone_temp$INDEX %in% test_ids, ]
 test1 <- test %>% select(-c("ANNUAL")) 
 vars <- as.matrix(train[, input$variable_choice])
  
plot_ly(data = test1, y = ~predict(model1(),test1), x = ~test$ANNUAL,
               type = "scatter", mode = "markers",
                marker = list(size = 5,
                              color = '#FFFFFF',
                              line = list(color = '#EA6345', 
                                          width = 2))) %>% 
   layout(title = '',
          yaxis = list(zeroline = FALSE, title = "Predicted Ozone Concentration (ppm)", titlefont = list(
   family = "Lucida Console, Courier New, monospace", size = 12, color = "#FFFFFF"), tickfont = list(
   family = "Lucida Console, Courier New, monospace", size = 10, color = "#FFFFFF"), color =  "white", size = 2),
    xaxis = list(zeroline = FALSE, title = "Actual Ozone Concentration (ppm)", titlefont = list(
   family = "Lucida Console, Courier New, monospace", size = 12, color = "#FFFFFF"), tickfont = list(
   family = "Lucida Console, Courier New, monospace", size = 10, color = "#FFFFFF"), color =  "white", size = 7)) %>%
   layout(plot_bgcolor='#678EB9', paper_bgcolor='#678EB9')

  
})
```

###

```{r histogram}
renderPlotly({
    set.seed(42)
 train_ids <- sample(all_ids, length(ozone_temp$INDEX)*(input$slider/100))
 train <- ozone_temp[ozone_temp$INDEX %in% train_ids , ]
 test <- ozone_temp[ozone_temp$INDEX %in% test_ids, ]
 test1 <- test %>% select(-c("ANNUAL")) 
 vars <- as.matrix(train[, input$variable_choice])

plot_ly(test, x = ~round(residuals(model1()),2), type = "histogram", marker = list(color = "#EA6345",
                            line = list(color = "#FFFFFF", width = 1))) %>%   layout(title = '',
         yaxis = list(zeroline = FALSE, title = "frequency",  titlefont = list(
  family = "Lucida Console, Courier New, monospace", size = 12, color = "#FFFFFF"), 
  tickfont = list(
  family = "Lucida Console, Courier New, monospace", size = 10, color = "#FFFFFF"), color =  "white"),
         xaxis = list(zeroline = FALSE, title = "residual",  titlefont = list(
  family = "Lucida Console, Courier New, monospace", size = 12, color = "#FFFFFF"), 
  tickfont = list(
  family = "Lucida Console, Courier New, monospace", size = 10, color = "#FFFFFF"), color =  "white")) %>%
  layout(plot_bgcolor='#678EB9', paper_bgcolor='#678EB9')


})
```


```{css}

```
